---
- name: Create a new user and set up SSH
  hosts: all
  become: yes
  become_user: root
  vars:
    username: deployer
    public_key: deployer.pub
  tasks:
  - name: Add the new user
    user:
      name: "{{ username }}"
      state: present
      shell: /bin/bash
      create_home: yes
  - name: Add user to sudo group
    user:
      name: "{{ username }}"
      groups: sudo
      append: yes
  - name: Create .ssh directory
    file:
      path: "/home/{{ username }}/.ssh"
      state: directory
      mode: '0700'
      owner: "{{ username }}"
      group: "{{ username }}"
  - name: Create authorized_keys file
    copy:
      src: "{{ public_key }}"
      dest: "/home/{{ username }}/.ssh/authorized_keys"
      mode: '0600'
      owner: "{{ username }}"
      group: "{{ username }}"

